apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: greetings
---

apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: uppercase
spec:
  protocol: grpc
  input: greetings
  container:
    image: sk8s/grpc-py:v0001
    env:
    - name: GRPC_PORT
      value: 10382
