apiVersion: v1
kind: Service
metadata:
  name: http-gateway-debug
  labels:
    app: riff
    component: http-gateway
spec:
  type: NodePort
  ports:
  - name: delve
    port: 2345
    nodePort: 30100
    targetPort: 2345
  selector:
    component: http-gateway
