apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: names
---

apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: greetings
---

apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: wordcount
spec:
  protocol: stdio
  input: names
  output: greetings
  container:
    image: sk8s/wordcount:v0001
